export const SAMPLE_MATCHES = [
    {
        id: 1,
        username: "Camilla",
        image: require("../assets/images/girl1.jpg"),
        isOnline: true,
        lastMessage: "Hope you are having a good day!",
        lastMessageTime: "4:52 pm",
    },
    {
        id: 2,
        username: "John",
        image: require("../assets/images/guy1.jpg"),
        isOnline: false,
        lastMessage: "Where do you live?",
        lastMessageTime: "12:52 pm",
    },
    {
        id: 3,
        username: "Lisa",
        image: require("../assets/images/girl2.jpg"),
        isOnline: true,
        lastMessage: "Yes",
        lastMessageTime: "10:00 am",
    },
    {
        id: 4,
        username: "Muhammad",
        image: require("../assets/images/guy2.jpg"),
        isOnline: false,
        lastMessage: "What is your name?",
        lastMessageTime: "3:12 pm",
    },
    {
        id: 5,
        username: "Sofia",
        image: require("../assets/images/girl3.jpg"),
        isOnline: true,
        lastMessage: "Got it",
        lastMessageTime: "7:03 am",
    },
    {
        id: 6,
        username: "David",
        image: require("../assets/images/guy3.jpg"),
        isOnline: false,
        lastMessage: "I dont remember",
        lastMessageTime: "11:13 am",
    },
    {
        id: 7,
        username: "Camilla",
        image: require("../assets/images/girl1.jpg"),
        isOnline: true,
        lastMessage: "Hope you are having a good day!",
        lastMessageTime: "4:52 pm",
    },
    {
        id: 8,
        username: "John",
        image: require("../assets/images/guy1.jpg"),
        isOnline: false,
        lastMessage: "Where do you live?",
        lastMessageTime: "12:52 pm",
    },
    {
        id: 9,
        username: "Lisa",
        image: require("../assets/images/girl2.jpg"),
        isOnline: true,
        lastMessage: "Yes",
        lastMessageTime: "10:00 am",
    },
    {
        id: 10,
        username: "Muhammad",
        image: require("../assets/images/guy2.jpg"),
        isOnline: false,
        lastMessage: "What is your name?",
        lastMessageTime: "3:12 pm",
    },
    {
        id: 11,
        username: "Sofia",
        image: require("../assets/images/girl3.jpg"),
        isOnline: true,
        lastMessage: "Got it",
        lastMessageTime: "7:03 am",
    },
    {
        id: 12,
        username: "David",
        image: require("../assets/images/guy3.jpg"),
        isOnline: false,
        lastMessage: "I dont remember",
        lastMessageTime: "11:13 am",
    },
];

export default {
    SAMPLE_MATCHES,
};
